services:
  portainer:
    image: portainer/portainer-ce:2.39.4
    container_name: portainer

    restart: unless-stopped

    ports:
      - "9000:9000"

    volumes:
      - ../../../data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - eil-network

networks:
  eil-network:
    external: true
