services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION}

    container_name: ${CONTAINER_NAME}

    restart: unless-stopped

    ports:
      - "${PORTAINER_PORT}:9000"

    volumes:
      - ${DATA_PATH}:/data
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - eil-network

networks:
  eil-network:
    external: true
